#!/bin/bash

G1=$1
G2=$2
mode=M
method=$3
k=$4
N=$5



sbatch  -p ioannidis --mem 1g   --time 2:00:00 compDistance   data/$G1/"attr_"$mode$k  data/$G2/"attr_"$mode$k  data/$G1/"Dist_"$G2$mode$k  data/$G1/$G2"_"$method  $N 

