#!/bin/bash

#SBATCH --nodes=1
#SBATCH --exclusive 
#SBATCH --job-name=GM
#SBATCH --tasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem=120Gb
#SBACTH --time=4320
#SBATCH --output=slurm-logs/GM%j.out
#SBATCH --error=slurm-logs/GM%j.err

GRAPH1=$1
GRAPH2=$2
iter=500
N=$3
PSolver=ParallelSolver
LSolver=LocalL1Solver
p=1
prepMod=all #Other choices WL5 or WL4 or all, neighbor
resume=$4

sbatch  -p ioannidis iter_batch_GM  data/$GRAPH1/$GRAPH2"_"$prepMod    data/traces/"GM_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N  data/RDDs/"GM_"$PSolver$LSolver$GRAPH1$GRAPH2$p"_N"$N  data/$GRAPH1/objectives_$GRAPH2"_"$prepMod checkpointdir  $N data/logfiles/"GM_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N $iter $LSolver  $PSolver $p  $resume  false  dummy

#for i in `seq 1 10`;
#do

#echo $i
#./iter_batch_GM  data/$GRAPH1/$GRAPH2"_"$prepMod    data/traces/"GM_adapRho_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N  data/RDDs/"GM_adapRho_"$PSolver$LSolver$GRAPH1$GRAPH2$p"_N"$N  data/$GRAPH1/objectives_$GRAPH2"_"$prepMod checkpointdir  $N data/logfiles/"GM_adapRho_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N $iter $LSolver  $PSolver $p  $resume

#done





