#!/bin/bash

#SBATCH --nodes=1
#SBATCH --exclusive 
#SBATCH --job-name=GM
#SBATCH --tasks=1
#SBATCH --output=slurm-logs/GM%j.out
#SBATCH --error=slurm-logs/GM%j.err

GRAPH1=$1
GRAPH2=$2
iter=1
N=$3
PSolver=ParallelSolver2norm
LSolver=LocalLSSolver
p=2
prepMod=all  #Other choices WL5 or WL4 or all, neighbor
#resume
linear=true 
lambda_lin=$4
masterIP=$5

./mstr_iter_batch_GM  data/$GRAPH1/$GRAPH2"_"$prepMod    data/traces/"GM_LinTerm"$lambda_lin"_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N  data/RDDs/"GM_LinTerm"$lambda_lin"_"$PSolver$LSolver$GRAPH1$GRAPH2$p"_N"$N  data/$GRAPH1/objectives_$GRAPH2"_"$prepMod checkpointdir  $N data/logfiles/"GM_LinTerm"$lambda_lin"_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N $iter $LSolver  $PSolver $p  false  $linear data/$GRAPH1/Dist_$GRAPH2"M2" $lambda_lin $masterIP

for i in `seq 1 20`;
do
    echo running for $i time 
  ./mstr_iter_batch_GM  data/$GRAPH1/$GRAPH2"_"$prepMod    data/traces/"GM_LinTerm"$lambda_lin"_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N  data/RDDs/"GM_LinTerm"$lambda_lin"_"$PSolver$LSolver$GRAPH1$GRAPH2$p"_N"$N  data/$GRAPH1/objectives_$GRAPH2"_"$prepMod checkpointdir  $N data/logfiles/"GM_LinTerm"$lambda_lin"_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N $iter $LSolver  $PSolver $p  true  $linear data/$GRAPH1/Dist_$GRAPH2"M2" $lambda_lin $masterIP
done 
#for i in `seq 1 10`;
#do

#echo $i
#./iter_batch_GM  data/$GRAPH1/$GRAPH2"_"$prepMod    data/traces/"GM_adapRho_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N  data/RDDs/"GM_adapRho_"$PSolver$LSolver$GRAPH1$GRAPH2$p"_N"$N  data/$GRAPH1/objectives_$GRAPH2"_"$prepMod checkpointdir  $N data/logfiles/"GM_adapRho_"$PSolver$LSolver$GRAPH1$GRAPH2"p"$p"_N"$N $iter $LSolver  $PSolver $p  $resume

#done





